export type Page =
  | 'dashboard'
  | 'funcionarios'
  | 'admitir'
  | 'organograma'
  | 'ponto'
  | 'holerite'
  | 'folha'
  | 'ats'
  | 'performance'
  | 'ferias'
  | 'beneficios'
  | 'treinamentos'
  | 'clima'
  | 'auditoria'
  | 'advertencias';
