import { memo, useCallback, useEffect, useMemo, useRef, useState, type DragEvent, type PointerEvent } from 'react';
import { useVirtualizer } from '@tanstack/react-virtual';
import { io, type Socket } from 'socket.io-client';
import { API_BASE, apiFetch, apiFormData } from '../services/api';
import { ATS_STAGES, type AtsBoardResponse, type AtsCard, type AtsStage, type AtsVacancy, type ChatMessage, type PresenceUser, type RemoteCursor } from '../types/ats';
import { useAuth } from '../context/useAuth';

const stageMeta:Record<AtsStage,{label:string;color:string;soft:string}> = {
  APLICACAO:{label:'Aplicação',color:'bg-slate-500',soft:'bg-slate-100 text-slate-600'},
  TRIAGEM:{label:'Triagem',color:'bg-blue-500',soft:'bg-blue-50 text-blue-700'},
  ENTREVISTA_TECNICA:{label:'Entrevista técnica',color:'bg-violet-500',soft:'bg-violet-50 text-violet-700'},
  FIT_CULTURAL:{label:'Fit cultural',color:'bg-fuchsia-500',soft:'bg-fuchsia-50 text-fuchsia-700'},
  PROPOSTA:{label:'Proposta',color:'bg-amber-500',soft:'bg-amber-50 text-amber-700'},
  CONTRATADO:{label:'Contratado',color:'bg-emerald-500',soft:'bg-emerald-50 text-emerald-700'},
};

function initials(name:string):string { return name.split(/\s+/).slice(0,2).map((word)=>word[0]).join('').toUpperCase(); }
function formatDate(value:string|null):string { return value ? new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value)) : ''; }

const CandidateCard = memo(function CandidateCard({card,lockedBy,onOpen,onDragStart,onDragEnd,readOnly}:{card:AtsCard;lockedBy?:string;onOpen:(card:AtsCard)=>void;onDragStart:(event:DragEvent,card:AtsCard)=>void;onDragEnd:(card:AtsCard)=>void;readOnly:boolean}) {
  return <article
    draggable={!readOnly&&!lockedBy}
    onDragStart={(event)=>onDragStart(event,card)} onDragEnd={()=>onDragEnd(card)} onClick={()=>onOpen(card)}
    className={`group h-[164px] cursor-pointer rounded-xl border bg-white p-3.5 shadow-sm transition hover:-translate-y-0.5 hover:border-teal-300 hover:shadow-md ${lockedBy?'border-amber-300 opacity-70':'border-slate-200'} ${readOnly?'cursor-default':''}`}
  >
    <div className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#102a43] text-xs font-bold text-white">{initials(card.nome)}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h3 className="truncate text-sm font-semibold text-slate-800">{card.nome}</h3><p className="truncate text-[11px] text-slate-400">{card.headline||card.email}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[11px] font-bold ${card.match_score>=80?'bg-emerald-50 text-emerald-700':card.match_score>=60?'bg-blue-50 text-blue-700':'bg-slate-100 text-slate-600'}`}>{card.match_score}%</span></div></div></div>
    <div className="mt-3 flex h-6 gap-1.5 overflow-hidden">{card.skills.slice(0,3).map((skill)=><span key={skill} className="shrink-0 rounded-md bg-slate-100 px-2 py-1 text-[10px] font-medium text-slate-600">{skill}</span>)}{card.skills.length>3&&<span className="text-[10px] text-slate-400">+{card.skills.length-3}</span>}</div>
    {lockedBy?<p className="mt-3 truncate rounded-md bg-amber-50 px-2 py-1 text-[10px] font-medium text-amber-700">Em movimento por {lockedBy}</p>:<div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-2.5 text-[10px] text-slate-400"><span>{card.origem.replaceAll('_',' ')}</span><span>{card.proxima_entrevista?`Entrevista ${formatDate(card.proxima_entrevista)}`:`${card.mensagens} mensagem(ns)`}</span></div>}
  </article>;
});

const VirtualColumn = memo(function VirtualColumn({stage,cards,locks,readOnly,onOpen,onDrop,onDragStart,onDragEnd}:{stage:AtsStage;cards:AtsCard[];locks:Map<number,string>;readOnly:boolean;onOpen:(card:AtsCard)=>void;onDrop:(stage:AtsStage)=>void;onDragStart:(event:DragEvent,card:AtsCard)=>void;onDragEnd:(card:AtsCard)=>void}) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const getKey = useCallback((index:number)=>cards[index]?.candidatura_id??index,[cards]);
  // TanStack Virtual gerencia seu proprio cache de medidas; o React Compiler nao deve memoizar este hook.
  // eslint-disable-next-line react-hooks/incompatible-library
  const virtualizer = useVirtualizer({count:cards.length,getScrollElement:()=>scrollRef.current,estimateSize:()=>174,overscan:4,getItemKey:getKey});
  const meta=stageMeta[stage];
  return <section className="flex h-[68vh] w-[310px] shrink-0 flex-col overflow-hidden rounded-2xl border border-slate-200 bg-slate-100/70" onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>{event.preventDefault();onDrop(stage);}}>
    <header className="flex items-center justify-between border-b border-slate-200 bg-white px-4 py-3"><div className="flex items-center gap-2"><span className={`h-2.5 w-2.5 rounded-full ${meta.color}`}/><h2 className="text-sm font-semibold text-slate-700">{meta.label}</h2></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-500">{cards.length}</span></header>
    <div ref={scrollRef} className="min-h-0 flex-1 overflow-y-auto p-3"><div className="relative w-full" style={{height:`${virtualizer.getTotalSize()}px`}}>{virtualizer.getVirtualItems().map((item)=>{const card=cards[item.index];if(!card)return null;return <div key={item.key} data-index={item.index} ref={virtualizer.measureElement} className="absolute left-0 top-0 w-full pb-2.5" style={{transform:`translateY(${item.start}px)`}}><CandidateCard card={card} lockedBy={locks.get(card.candidatura_id)||card.bloqueado_por_nome||undefined} onOpen={onOpen} onDragStart={onDragStart} onDragEnd={onDragEnd} readOnly={readOnly}/></div>;})}</div>{cards.length===0&&<div className="flex h-40 items-center justify-center rounded-xl border-2 border-dashed border-slate-200 text-xs text-slate-400">Solte um candidato aqui</div>}</div>
  </section>;
});

function InterviewModal({card,onClose,onSaved}:{card:AtsCard;onClose:()=>void;onSaved:()=>void}) {
  const tomorrow=new Date(Date.now()+24*60*60*1000);tomorrow.setHours(10,0,0,0);
  const [start,setStart]=useState(tomorrow.toISOString().slice(0,16));
  const [duration,setDuration]=useState(60);const [provider,setProvider]=useState('INTERNO');const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  const save=async()=>{setSaving(true);setError('');try{const begin=new Date(start);const end=new Date(begin.getTime()+duration*60000);await apiFetch('/ats/entrevistas',{method:'POST',body:JSON.stringify({candidaturaId:card.candidatura_id,titulo:`Entrevista técnica · ${card.nome}`,tipo:'TECNICA',inicioEm:begin.toISOString(),fimEm:end.toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,provedor:provider,participantes:[{nome:card.nome,email:card.email}]})});onSaved();}catch(e){setError(e instanceof Error?e.message:'Falha ao agendar.');}finally{setSaving(false);}};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose();}}><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-violet-600">Agendamento rápido</p><h2 className="mt-1 font-serif text-xl text-[#102a43]">Entrevista com {card.nome}</h2></div><button onClick={onClose} className="text-xl text-slate-400">×</button></div>{error&&<p className="mt-4 rounded-lg bg-red-50 p-3 text-xs text-red-700">{error}</p>}<div className="mt-5 space-y-4"><label className="block text-xs font-semibold text-slate-600">Início<input type="datetime-local" value={start} onChange={(e)=>setStart(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-600">Duração<select value={duration} onChange={(e)=>setDuration(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value={30}>30 min</option><option value={45}>45 min</option><option value={60}>60 min</option><option value={90}>90 min</option></select></label><label className="text-xs font-semibold text-slate-600">Calendário<select value={provider} onChange={(e)=>setProvider(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="INTERNO">Sala interna</option><option value="GOOGLE">Google</option><option value="OUTLOOK">Outlook</option></select></label></div></div><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-600">Agora não</button><button onClick={save} disabled={saving} className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving?'Agendando…':'Confirmar entrevista'}</button></div></div></div>;
}

function CandidateDrawer({card,socket,onClose,onSchedule}:{card:AtsCard;socket:Socket|null;onClose:()=>void;onSchedule:()=>void}) {
  const [messages,setMessages]=useState<ChatMessage[]>([]);const [text,setText]=useState('');const [error,setError]=useState('');
  useEffect(()=>{void apiFetch<ChatMessage[]>(`/ats/candidaturas/${card.candidatura_id}/mensagens`).then(setMessages).catch((e)=>setError(e instanceof Error?e.message:'Falha no chat.'));socket?.emit('chat:join',{candidaturaId:card.candidatura_id});const listener=(message:ChatMessage)=>{if(message.candidatura_id===card.candidatura_id)setMessages((current)=>current.some((item)=>item.id===message.id)?current:[...current,message]);};socket?.on('chat:message',listener);return()=>{socket?.off('chat:message',listener);};},[card.candidatura_id,socket]);
  const send=()=>{const message=text.trim();if(!message)return;setText('');const payload={candidaturaId:card.candidatura_id,mensagem:message,idempotencia:crypto.randomUUID()};if(socket?.connected)socket.timeout(5000).emit('chat:send',payload,(err:unknown,response:{ok?:boolean;error?:string})=>{if(err||!response?.ok)setError(response?.error||'Falha ao enviar.');});else void apiFetch(`/ats/candidaturas/${card.candidatura_id}/mensagens`,{method:'POST',body:JSON.stringify(payload)}).then((row)=>setMessages((current)=>[...current,row as ChatMessage])).catch((e)=>setError(e instanceof Error?e.message:'Falha ao enviar.'));};
  return <aside className="fixed inset-y-0 right-0 z-40 flex w-full max-w-md flex-col border-l border-slate-200 bg-white shadow-2xl"><header className="border-b border-slate-100 p-5"><div className="flex items-start justify-between"><div className="flex gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#102a43] text-sm font-bold text-white">{initials(card.nome)}</span><div><h2 className="font-serif text-xl text-[#102a43]">{card.nome}</h2><p className="text-xs text-slate-400">{card.email}</p></div></div><button onClick={onClose} className="text-2xl text-slate-400">×</button></div><div className="mt-4 flex flex-wrap gap-1.5">{card.skills.map((skill)=><span key={skill} className="rounded-md bg-teal-50 px-2 py-1 text-[10px] font-semibold text-teal-700">{skill}</span>)}</div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={onSchedule} className="rounded-xl bg-violet-600 px-3 py-2 text-xs font-semibold text-white">Agendar entrevista</button><div className="rounded-xl bg-slate-50 px-3 py-2 text-center text-xs font-semibold text-slate-600">Match {card.match_score}%</div></div></header><div className="flex-1 overflow-y-auto bg-slate-50 p-4"><p className="mb-3 text-[10px] font-semibold uppercase tracking-wider text-slate-400">Central de comunicação</p>{error&&<p className="mb-3 text-xs text-red-600">{error}</p>}<div className="space-y-2">{messages.map((message)=><div key={message.id} className={`max-w-[85%] rounded-xl px-3 py-2 text-sm ${message.remetente_tipo==='RECRUTADOR'?'ml-auto bg-[#102a43] text-white':'bg-white text-slate-700 shadow-sm'}`}><p>{message.mensagem}</p><p className="mt-1 text-[9px] opacity-50">{formatDate(message.criada_em)}</p></div>)}{messages.length===0&&<p className="py-10 text-center text-xs text-slate-400">Nenhuma mensagem. Inicie a conversa.</p>}</div></div><footer className="flex gap-2 border-t border-slate-100 p-4"><input value={text} onChange={(e)=>setText(e.target.value)} onKeyDown={(e)=>{if(e.key==='Enter')send();}} placeholder="Escreva uma mensagem…" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:border-teal-500"/><button onClick={send} className="rounded-xl bg-teal-600 px-4 py-2 text-sm font-semibold text-white">Enviar</button></footer></aside>;
}

export default function AtsRecrutamento(){
  const {token}=useAuth();
  const [vacancies,setVacancies]=useState<AtsVacancy[]>([]);const [vacancyId,setVacancyId]=useState<number|null>(null);const [board,setBoard]=useState<AtsBoardResponse|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [presence,setPresence]=useState<PresenceUser[]>([]);const [cursors,setCursors]=useState<Map<number,RemoteCursor>>(new Map());const [locks,setLocks]=useState<Map<number,string>>(new Map());const [selected,setSelected]=useState<AtsCard|null>(null);const [scheduleCard,setScheduleCard]=useState<AtsCard|null>(null);const [search,setSearch]=useState('');const [minScore,setMinScore]=useState(0);const [uploading,setUploading]=useState(false);const socketRef=useRef<Socket|null>(null);const dragging=useRef<AtsCard|null>(null);const boardRef=useRef<HTMLDivElement>(null);const cursorFrame=useRef<number|null>(null);
  const loadVacancies=useCallback(async()=>{const rows=await apiFetch<AtsVacancy[]>('/ats/vagas');setVacancies(rows);setVacancyId((current)=>current??rows[0]?.id??null);},[]);
  const loadBoard=useCallback(async()=>{if(!vacancyId)return;setLoading(true);try{setBoard(await apiFetch<AtsBoardResponse>(`/ats/vagas/${vacancyId}/kanban`));setError('');}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar Kanban.');}finally{setLoading(false);}},[vacancyId]);
  useEffect(()=>{void loadVacancies().catch((e)=>{setError(e instanceof Error?e.message:'Falha ao carregar vagas.');setLoading(false);});},[loadVacancies]);useEffect(()=>{void loadBoard();},[loadBoard]);
  useEffect(()=>{if(!token)return;const socket=io(API_BASE,{auth:{token},transports:['websocket','polling'],reconnectionDelayMax:4000,autoConnect:false});socketRef.current=socket;socket.on('presence:update',(rows:PresenceUser[])=>setPresence(rows));socket.on('cursor:update',(cursor:RemoteCursor)=>setCursors((current)=>new Map(current).set(cursor.userId,cursor)));socket.on('card:locked',(event:{candidaturaId:number;user:PresenceUser})=>setLocks((current)=>new Map(current).set(event.candidaturaId,event.user.name)));socket.on('card:unlocked',(event:{candidaturaId:number})=>setLocks((current)=>{const next=new Map(current);next.delete(event.candidaturaId);return next;}));socket.on('card:moved',(event:{candidaturaId:number;etapa:AtsStage;posicao:string;versao:number})=>{setLocks((current)=>{const next=new Map(current);next.delete(event.candidaturaId);return next;});setBoard((current)=>current?{...current,cards:current.cards.map((card)=>card.candidatura_id===event.candidaturaId?{...card,etapa:event.etapa,posicao:event.posicao,versao:event.versao,bloqueado_por_nome:null}:card)}:current);});socket.on('interview:scheduled',()=>setNotice('Entrevista agendada e equipe atualizada em tempo real.'));socket.on('connect_error',(e)=>setError(`Tempo real indisponível: ${e.message}`));const connectTimer=window.setTimeout(()=>socket.connect(),0);return()=>{window.clearTimeout(connectTimer);socket.disconnect();socketRef.current=null;};},[token]);
  useEffect(()=>{if(!vacancyId||!socketRef.current)return;socketRef.current.emit('vaga:join',{vagaId:vacancyId},(response:{ok?:boolean;error?:string})=>{if(!response.ok)setError(response.error||'Falha ao entrar na vaga.');});setPresence([]);setCursors(new Map());setLocks(new Map());},[vacancyId]);
  useEffect(()=>{const timer=window.setInterval(()=>setCursors((current)=>new Map([...current].filter(([,cursor])=>Date.now()-cursor.at<3500))),1500);return()=>window.clearInterval(timer);},[]);
  const filtered=useMemo(()=>{const term=search.trim().toLowerCase();return (board?.cards??[]).filter((card)=>card.match_score>=minScore&&(!term||`${card.nome} ${card.email} ${card.headline??''} ${card.skills.join(' ')}`.toLowerCase().includes(term)));},[board,search,minScore]);
  const byStage=useMemo(()=>Object.fromEntries(ATS_STAGES.map((stage)=>[stage,filtered.filter((card)=>card.etapa===stage).sort((a,b)=>Number(a.posicao)-Number(b.posicao))])) as Record<AtsStage,AtsCard[]>,[filtered]);
  const readOnly=board?.vacancy.permissao==='LEITOR'||board?.vacancy.permissao==='ENTREVISTADOR';
  const dragStart=(event:DragEvent,card:AtsCard)=>{dragging.current=card;event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',String(card.candidatura_id));socketRef.current?.emit('card:lock',{vagaId:card.vaga_id,candidaturaId:card.candidatura_id,versao:card.versao},(response:{ok?:boolean;error?:string})=>{if(!response.ok){setError(response.error||'Card bloqueado.');dragging.current=null;}});};
  const dragEnd=(card:AtsCard)=>{socketRef.current?.emit('card:unlock',{vagaId:card.vaga_id,candidaturaId:card.candidatura_id});dragging.current=null;};
  const drop=async(stage:AtsStage)=>{const card=dragging.current;if(!card||card.etapa===stage)return;const payload={vagaId:card.vaga_id,candidaturaId:card.candidatura_id,etapa:stage,posicao:Date.now(),versao:card.versao,correlationId:crypto.randomUUID()};try{if(socketRef.current?.connected){await new Promise<void>((resolve,reject)=>socketRef.current?.timeout(5000).emit('card:move',payload,(timeout:unknown,response:{ok?:boolean;error?:string})=>timeout||!response?.ok?reject(new Error(response?.error||'Tempo esgotado.')):resolve()));}else{await apiFetch(`/ats/candidaturas/${card.candidatura_id}/mover`,{method:'PATCH',body:JSON.stringify(payload)});await loadBoard();}if(stage==='ENTREVISTA_TECNICA')setScheduleCard(card);}catch(e){setError(e instanceof Error?e.message:'Conflito ao mover card.');await loadBoard();}finally{dragging.current=null;}};
  const upload=async(file:File)=>{if(!vacancyId)return;setUploading(true);setError('');try{const form=new FormData();form.append('curriculo',file);const result=await apiFormData<{match:{score:number};profile:{nome:string}}>(`/ats/vagas/${vacancyId}/curriculos`,form);setNotice(`${result.profile.nome} processado com match de ${result.match.score}%.`);await loadBoard();}catch(e){setError(e instanceof Error?e.message:'Falha ao processar currículo.');}finally{setUploading(false);}};
  const pointerMove=(event:PointerEvent<HTMLDivElement>)=>{if(cursorFrame.current!==null)return;const x=event.clientX,y=event.clientY;cursorFrame.current=requestAnimationFrame(()=>{cursorFrame.current=null;const rect=boardRef.current?.getBoundingClientRect();if(!rect)return;socketRef.current?.volatile.emit('cursor:move',{x:Math.max(0,Math.min(1,(x-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(y-rect.top)/rect.height))});});};
  return <div ref={boardRef} onPointerMove={pointerMove} className="relative mx-auto max-w-[1800px] space-y-5 overflow-hidden text-slate-800">{[...cursors.values()].map((cursor)=><div key={cursor.userId} className="pointer-events-none absolute z-50 transition-all duration-100" style={{left:`${cursor.x*100}%`,top:`${cursor.y*100}%`}}><span className="block h-3 w-3 rotate-45" style={{backgroundColor:cursor.color}}/><span className="ml-2 rounded px-1.5 py-0.5 text-[9px] font-semibold text-white" style={{backgroundColor:cursor.color}}>{cursor.name}</span></div>)}
    <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-teal-700"><span className="h-2 w-2 rounded-full bg-teal-500"/>Talent acquisition workspace</div><h1 className="font-serif text-3xl font-semibold text-[#102a43]">Recrutamento & Seleção</h1><p className="mt-1 text-sm text-slate-500">Pipeline colaborativo, match de currículos e comunicação em tempo real.</p></div><div className="flex flex-wrap items-center gap-2"><div className="flex -space-x-2">{presence.slice(0,5).map((person)=><span key={person.id} title={person.name} className="flex h-8 w-8 items-center justify-center rounded-full border-2 border-white text-[10px] font-bold text-white" style={{backgroundColor:person.color}}>{initials(person.name)}</span>)}</div><span className="mr-2 text-xs text-slate-400">{presence.length} online</span><label className={`cursor-pointer rounded-xl bg-teal-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-teal-700 ${uploading?'pointer-events-none opacity-50':''}`}>{uploading?'Analisando currículo…':'Adicionar currículo'}<input type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="hidden" onChange={(e)=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label></div></header>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}<button onClick={()=>setError('')} className="float-right">×</button></div>}{notice&&<div className="rounded-xl border border-teal-200 bg-teal-50 px-4 py-3 text-sm text-teal-700">{notice}<button onClick={()=>setNotice('')} className="float-right">×</button></div>}
    <section className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm lg:flex-row lg:items-center"><select value={vacancyId??''} onChange={(e)=>setVacancyId(Number(e.target.value))} className="min-w-64 rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-700">{vacancies.map((vacancy)=><option key={vacancy.id} value={vacancy.id}>{vacancy.titulo} · {vacancy.departamento}</option>)}</select><div className="h-7 w-px bg-slate-200 max-lg:hidden"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Buscar nome, e-mail ou skill…" className="min-w-0 flex-1 rounded-xl bg-slate-50 px-4 py-2.5 text-sm outline-none ring-1 ring-slate-200 focus:ring-teal-400"/><select value={minScore} onChange={(e)=>setMinScore(Number(e.target.value))} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-600"><option value={0}>Todos os matches</option><option value={60}>Match ≥ 60%</option><option value={80}>Match ≥ 80%</option></select><span className="rounded-xl bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-500">{filtered.length} talento(s)</span></section>
    {loading?<div className="h-[68vh] animate-pulse rounded-2xl bg-slate-200/70"/>:vacancies.length===0?<div className="rounded-2xl border border-dashed border-slate-300 bg-white py-20 text-center text-sm text-slate-400">Nenhuma vaga disponível para seu usuário.</div>:<div className="overflow-x-auto pb-3"><div className="flex min-w-max gap-3">{ATS_STAGES.map((stage)=><VirtualColumn key={stage} stage={stage} cards={byStage[stage]} locks={locks} readOnly={Boolean(readOnly)} onOpen={setSelected} onDrop={drop} onDragStart={dragStart} onDragEnd={dragEnd}/>)}</div></div>}
    {selected&&<CandidateDrawer card={selected} socket={socketRef.current} onClose={()=>setSelected(null)} onSchedule={()=>setScheduleCard(selected)}/>} {scheduleCard&&<InterviewModal card={scheduleCard} onClose={()=>setScheduleCard(null)} onSaved={()=>{setScheduleCard(null);setNotice('Entrevista agendada com sucesso.');void loadBoard();}}/>}
  </div>;
}
