import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiFetch } from '../services/api';
import type { ClimateDashboard, ClimatePublication, PersonSuggestion } from '../types/climate';

const number = (value:unknown):number => Number(value ?? 0);
const initials = (name:string):string => name.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();
const dateLabel = (value:string):string => new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const categoryLabel:Record<string,string>={COLABORACAO:'Colaboração',INOVACAO:'Inovação',ATITUDE_CLIENTE:'Atitude cliente',LIDERANCA:'Liderança',ESPIRITO_EQUIPE:'Espírito de equipe'};

function normalize(data:ClimateDashboard):ClimateDashboard{
  return {...data,balance:{...data.balance,quantidade_total:number(data.balance?.quantidade_total),quantidade_utilizada:number(data.balance?.quantidade_utilizada),disponiveis:number(data.balance?.disponiveis)},feed:data.feed.map(item=>({...item,id:number(item.id),curtidas:number(item.curtidas),comentarios_total:number(item.comentarios_total),curtiu:Boolean(item.curtiu)})),comments:data.comments.map(item=>({...item,id:number(item.id),publicacao_id:number(item.publicacao_id)})),heatmap:data.heatmap.map(item=>({...item,respostas:number(item.respostas),enps:number(item.enps),media:number(item.media),positivos:number(item.positivos),neutros:number(item.neutros),negativos:number(item.negativos)})),kudosRanking:data.kudosRanking.map(item=>({...item,kudos:number(item.kudos)}))};
}

export default function ClimaComunicacao(){
  const[data,setData]=useState<ClimateDashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[notice,setNotice]=useState('');
  const[type,setType]=useState<'PUBLICACAO'|'KUDOS'>('PUBLICACAO');const[content,setContent]=useState('');const[mentionedIds,setMentionedIds]=useState<number[]>([]);const[suggestions,setSuggestions]=useState<PersonSuggestion[]>([]);const[mentionQuery,setMentionQuery]=useState<string|null>(null);const[recipientQuery,setRecipientQuery]=useState('');const[recipient,setRecipient]=useState<PersonSuggestion|null>(null);const[category,setCategory]=useState('COLABORACAO');const[publishing,setPublishing]=useState(false);
  const[commentDrafts,setCommentDrafts]=useState<Record<number,string>>({});const[score,setScore]=useState<number|null>(null);const[feedback,setFeedback]=useState('');const[voting,setVoting]=useState(false);const[loadingMore,setLoadingMore]=useState(false);
  const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);try{setData(normalize(await apiFetch<ClimateDashboard>('/clima/dashboard')));setError('')}catch(err){setError(err instanceof Error?err.message:'Falha ao carregar o mural.')}finally{if(!silent)setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const activeSearch=type==='KUDOS'&&recipientQuery&&!recipient?recipientQuery:mentionQuery;
  useEffect(()=>{if(activeSearch===null){setSuggestions([]);return}const timer=window.setTimeout(async()=>{try{setSuggestions(await apiFetch<PersonSuggestion[]>(`/clima/pessoas?busca=${encodeURIComponent(activeSearch)}`))}catch{setSuggestions([])}},180);return()=>window.clearTimeout(timer)},[activeSearch]);
  const commentsByPost=useMemo(()=>{const grouped=new Map<number,ClimateDashboard['comments']>();for(const comment of data?.comments??[]){const list=grouped.get(comment.publicacao_id)??[];list.push(comment);grouped.set(comment.publicacao_id,list)}return grouped},[data?.comments]);
  const onContent=(value:string)=>{setContent(value);const match=value.match(/(?:^|\s)@([\p{L}\d._-]{0,80})$/u);setMentionQuery(match?match[1]:null)};
  const chooseMention=(person:PersonSuggestion)=>{setContent(current=>current.replace(/@([\p{L}\d._-]{0,80})$/u,`@${person.nome} `));setMentionedIds(current=>current.includes(person.id)?current:[...current,person.id]);setMentionQuery(null);setSuggestions([])};
  const publish=async()=>{if(!content.trim())return;setPublishing(true);try{await apiFetch('/clima/publicacoes',{method:'POST',body:JSON.stringify({tipo:type,conteudo:content,destinatarioId:recipient?.id,categoriaKudos:category,mencionadosIds:mentionedIds,idempotencia:crypto.randomUUID()})});setContent('');setMentionedIds([]);setRecipient(null);setRecipientQuery('');setSuggestions([]);setNotice(type==='KUDOS'?'Kudos entregue — reconhecimento que vira cultura.':'Publicação compartilhada.');await load(true)}catch(err){setError(err instanceof Error?err.message:'Não foi possível publicar.')}finally{setPublishing(false)}};
  const toggleLike=async(post:ClimatePublication)=>{setData(current=>current?{...current,feed:current.feed.map(item=>item.id===post.id?{...item,curtiu:!item.curtiu,curtidas:Math.max(0,item.curtidas+(item.curtiu?-1:1))}:item)}:current);try{const result=await apiFetch<{liked:boolean;total:number}>(`/clima/publicacoes/${post.id}/curtida`,{method:'POST'});setData(current=>current?{...current,feed:current.feed.map(item=>item.id===post.id?{...item,curtiu:result.liked,curtidas:number(result.total)}:item)}:current)}catch(err){setError(err instanceof Error?err.message:'Falha ao curtir.');await load(true)}};
  const comment=async(postId:number)=>{const text=commentDrafts[postId]?.trim();if(!text)return;try{await apiFetch(`/clima/publicacoes/${postId}/comentarios`,{method:'POST',body:JSON.stringify({conteudo:text,mencionadosIds:[]})});setCommentDrafts(current=>({...current,[postId]:''}));await load(true)}catch(err){setError(err instanceof Error?err.message:'Falha ao comentar.')}};
  const loadMore=async()=>{if(!data?.nextCursor||loadingMore)return;setLoadingMore(true);try{const next=normalize(await apiFetch<ClimateDashboard>(`/clima/dashboard?cursor=${data.nextCursor}`));setData(current=>current?{...current,feed:[...current.feed,...next.feed],comments:[...current.comments,...next.comments],mentions:[...current.mentions,...next.mentions],nextCursor:next.nextCursor}:next)}catch(err){setError(err instanceof Error?err.message:'Falha ao carregar mais publicações.')}finally{setLoadingMore(false)}};
  const vote=async()=>{if(!data?.survey||score===null)return;setVoting(true);const key=`enps-ballot:${data.survey.id}`;try{let credential=sessionStorage.getItem(key);if(!credential){const issued=await apiFetch<{credencial:string}>(`/clima/pesquisas/${data.survey.id}/credencial`,{method:'POST'});credential=issued.credencial;sessionStorage.setItem(key,credential)}await apiFetch('/clima/enps/votos',{method:'POST',body:JSON.stringify({credencial:credential,nota:score,feedback})});sessionStorage.removeItem(key);setScore(null);setFeedback('');setNotice('Pulso recebido. Sua identidade não foi armazenada com o voto.');await load(true)}catch(err){setError(err instanceof Error?err.message:'Falha ao enviar o pulso.')}finally{setVoting(false)}};
  if(loading&&!data)return<p className="text-sm text-slate-500">Preparando o pulso da organização…</p>;
  return <div className="mx-auto max-w-[1500px] space-y-5"><header className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.2em] text-fuchsia-600">People Voice · Endomarketing</p><h1 className="mt-1 font-serif text-3xl font-semibold text-[#102f4a]">Pulso & Cultura</h1><p className="mt-1 text-sm text-slate-500">Reconhecimento público, escuta protegida e sinais coletivos de bem-estar.</p></div><div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><Avatar name={data?.actor.nome??'—'}/><div><p className="text-xs font-bold text-slate-800">{data?.actor.nome}</p><p className="text-[10px] text-slate-400">{data?.actor.departamento}</p></div><div className="ml-3 border-l border-slate-100 pl-4 text-right"><strong className="text-xl text-fuchsia-600">{data?.balance.disponiveis??0}</strong><p className="text-[9px] uppercase text-slate-400">Kudos disponíveis</p></div></div></header>
    {(error||notice)&&<div className={`flex justify-between rounded-xl border px-4 py-3 text-xs ${error?'border-rose-200 bg-rose-50 text-rose-700':'border-emerald-200 bg-emerald-50 text-emerald-700'}`}><span>{error||notice}</span><button onClick={()=>{setError('');setNotice('')}}>×</button></div>}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><main className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-2"><button onClick={()=>setType('PUBLICACAO')} className={`rounded-full px-3 py-1.5 text-[10px] font-bold ${type==='PUBLICACAO'?'bg-[#102f4a] text-white':'bg-slate-100 text-slate-500'}`}>Compartilhar</button><button onClick={()=>setType('KUDOS')} className={`rounded-full px-3 py-1.5 text-[10px] font-bold ${type==='KUDOS'?'bg-fuchsia-600 text-white':'bg-slate-100 text-slate-500'}`}>Dar Kudos ✦</button></div>
      {type==='KUDOS'&&<div className="relative mt-4 grid gap-3 sm:grid-cols-2"><div><label className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Reconhecer quem?</label>{recipient?<button onClick={()=>setRecipient(null)} className="mt-1 flex w-full items-center gap-2 rounded-xl border border-fuchsia-200 bg-fuchsia-50 p-2 text-left"><Avatar name={recipient.nome} small/><span className="flex-1 text-xs font-bold text-fuchsia-800">{recipient.nome}</span><span>×</span></button>:<input value={recipientQuery} onChange={event=>setRecipientQuery(event.target.value)} placeholder="Busque pelo nome" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-xs outline-none focus:border-fuchsia-400"/>}</div><label className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Valor reconhecido<select value={category} onChange={event=>setCategory(event.target.value)} className="mt-1 block w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-medium normal-case tracking-normal outline-none">{Object.entries(categoryLabel).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{!recipient&&recipientQuery&&<Suggestions people={suggestions} choose={person=>{setRecipient(person);setRecipientQuery(person.nome);setSuggestions([])}}/>}</div>}
      <div className="relative mt-4"><textarea value={content} onChange={event=>onContent(event.target.value)} rows={4} maxLength={4000} placeholder={type==='KUDOS'?'Conte o que essa pessoa fez de especial… Use @ para mencionar colegas.':'O que vale a pena compartilhar hoje? Use @ para mencionar alguém.'} className="w-full resize-none rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-relaxed outline-none transition focus:border-fuchsia-300 focus:bg-white"/>{mentionQuery!==null&&<Suggestions people={suggestions} choose={chooseMention}/>}</div><div className="mt-3 flex items-center justify-between"><span className="text-[9px] text-slate-400">{content.length}/4000 · análise exibida somente de forma agregada</span><button onClick={()=>void publish()} disabled={publishing||!content.trim()||(type==='KUDOS'&&!recipient)} className="rounded-xl bg-[#102f4a] px-5 py-2.5 text-xs font-bold text-white transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:bg-slate-200">{publishing?'Publicando…':type==='KUDOS'?'Entregar Kudos':'Publicar'}</button></div></section>
      {(data?.feed??[]).map(post=><article key={post.id} className={`climate-enter overflow-hidden rounded-2xl border bg-white shadow-sm ${post.tipo==='KUDOS'?'border-fuchsia-200':'border-slate-200'}`}>{post.tipo==='KUDOS'&&<div className="bg-gradient-to-r from-fuchsia-600 to-violet-600 px-5 py-2 text-[10px] font-bold uppercase tracking-[.14em] text-white">✦ Kudos · {categoryLabel[post.categoria_kudos??'']??post.categoria_kudos}</div>}<div className="p-5"><div className="flex items-center gap-3"><Avatar name={post.autor_nome}/><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-slate-900">{post.autor_nome}{post.tipo==='KUDOS'&&<span className="font-normal text-slate-400"> reconheceu </span>}{post.tipo==='KUDOS'&&<span className="text-fuchsia-700">{post.destinatario_nome}</span>}</p><p className="text-[9px] text-slate-400">{dateLabel(post.criado_em)}</p></div></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-700">{post.conteudo}</p><div className="mt-4 flex gap-5 border-t border-slate-100 pt-3"><button onClick={()=>void toggleLike(post)} className={`text-xs font-semibold ${post.curtiu?'text-fuchsia-600':'text-slate-500'}`}>{post.curtiu?'♥':'♡'} {post.curtidas}</button><span className="text-xs text-slate-400">◌ {post.comentarios_total} comentários</span></div>{(commentsByPost.get(post.id)??[]).map(item=><div key={item.id} className="mt-3 flex gap-2 rounded-xl bg-slate-50 p-3"><Avatar name={item.autor_nome} small/><div><p className="text-[10px] font-bold">{item.autor_nome}</p><p className="mt-0.5 text-xs text-slate-600">{item.conteudo}</p></div></div>)}<div className="mt-3 flex gap-2"><input value={commentDrafts[post.id]??''} onChange={event=>setCommentDrafts(current=>({...current,[post.id]:event.target.value}))} onKeyDown={event=>{if(event.key==='Enter')void comment(post.id)}} placeholder="Escreva um comentário…" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2 text-xs outline-none focus:border-fuchsia-300"/><button onClick={()=>void comment(post.id)} className="rounded-xl bg-slate-100 px-3 text-xs font-bold text-slate-600">Enviar</button></div></div></article>)}{!data?.feed.length&&<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-400">O mural está pronto para a primeira história da equipe.</div>}{data?.nextCursor&&<button onClick={()=>void loadMore()} disabled={loadingMore} className="w-full rounded-xl border border-slate-200 bg-white py-3 text-xs font-bold text-slate-500 shadow-sm disabled:opacity-60">{loadingMore?'Carregando…':'Carregar mais histórias'}</button>}</main>
      <aside className="space-y-4"><PulseCard data={data} score={score} setScore={setScore} feedback={feedback} setFeedback={setFeedback} voting={voting} vote={vote}/><ClimateCard data={data}/><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-sm font-bold text-slate-900">Destaques da semana</h2><span className="text-lg">✦</span></div><div className="mt-4 space-y-3">{data?.kudosRanking.map((item,index)=><div key={item.destinatario_id} className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-amber-100 text-xs font-bold text-amber-700">{index+1}</span><span className="min-w-0 flex-1 truncate text-xs font-semibold">{item.nome}</span><strong className="text-xs text-fuchsia-600">{item.kudos} Kudos</strong></div>)}{!data?.kudosRanking.length&&<p className="text-xs text-slate-400">Os reconhecimentos aparecerão aqui.</p>}</div></section></aside></div></div>
}

function Avatar({name,small=false}:{name:string;small?:boolean}){return <span className={`flex shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-fuchsia-500 to-violet-700 font-bold text-white ${small?'h-7 w-7 text-[9px]':'h-10 w-10 text-xs'}`}>{initials(name)}</span>}
function Suggestions({people,choose}:{people:PersonSuggestion[];choose:(person:PersonSuggestion)=>void}){return <div className="absolute left-0 right-0 top-full z-30 mt-1 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl">{people.map(person=><button key={person.id} onMouseDown={event=>event.preventDefault()} onClick={()=>choose(person)} className="flex w-full items-center gap-2 px-3 py-2 text-left hover:bg-fuchsia-50"><Avatar name={person.nome} small/><span className="text-xs font-semibold">{person.nome}</span><span className="ml-auto text-[9px] text-slate-400">{person.email}</span></button>)}{!people.length&&<p className="p-3 text-xs text-slate-400">Nenhuma pessoa encontrada.</p>}</div>}
function PulseCard({data,score,setScore,feedback,setFeedback,voting,vote}:{data:ClimateDashboard|null;score:number|null;setScore:(value:number)=>void;feedback:string;setFeedback:(value:string)=>void;voting:boolean;vote:()=>Promise<void>}){const survey=data?.survey;if(!survey)return null;return <section className="overflow-hidden rounded-2xl border border-violet-200 bg-white shadow-sm"><div className="bg-[#102f4a] p-5 text-white"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-violet-300">Pulso anônimo</p><span className="rounded-full bg-white/10 px-2 py-1 text-[9px]">{survey.taxa_participacao}% participação</span></div><h2 className="mt-2 text-base font-semibold">{survey.titulo}</h2><p className="mt-1 text-xs leading-5 text-slate-300">{survey.pergunta}</p></div>{survey.ja_respondeu?<div className="p-5 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-100 text-xl text-emerald-700">✓</div><p className="mt-2 text-sm font-bold">Pulso registrado</p><p className="mt-1 text-[10px] leading-4 text-slate-400">O banco registra participação e voto em domínios sem vínculo entre si.</p></div>:<div className="p-5"><div className="grid grid-cols-11 gap-1">{Array.from({length:11},(_,value)=><button key={value} onClick={()=>setScore(value)} className={`aspect-square rounded-md text-[10px] font-bold transition ${score===value?'scale-110 bg-fuchsia-600 text-white shadow':'bg-slate-100 text-slate-500 hover:bg-violet-100'}`}>{value}</button>)}</div><div className="mt-2 flex justify-between text-[8px] uppercase text-slate-400"><span>Não recomendaria</span><span>Recomendaria</span></div><textarea value={feedback} onChange={event=>setFeedback(event.target.value)} maxLength={2000} rows={3} placeholder="Comentário opcional — dados pessoais são removidos antes da criptografia." className="mt-4 w-full resize-none rounded-xl border border-slate-200 p-3 text-xs outline-none focus:border-fuchsia-300"/><button onClick={()=>void vote()} disabled={score===null||voting} className="mt-3 w-full rounded-xl bg-fuchsia-600 py-2.5 text-xs font-bold text-white disabled:bg-slate-200">{voting?'Protegendo e enviando…':'Enviar pulso protegido'}</button><p className="mt-3 text-center text-[8px] leading-4 text-slate-400">Credencial criptográfica · feedback AES-256-GCM · grupos mínimos de {survey.minimo_grupo}</p></div>}</section>}
function ClimateCard({data}:{data:ClimateDashboard|null}){const metric=data?.climateMetrics;const rows=data?.heatmap??[];return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-sm font-bold">Termômetro coletivo</h2>{metric&&<strong className={`${metric.enps>=50?'text-emerald-600':metric.enps>=0?'text-amber-600':'text-rose-600'}`}>eNPS {metric.enps}</strong>}</div>{metric?<><div className="mt-4 grid grid-cols-3 gap-2"><Mood value={metric.positivos} label="Positivo" color="bg-emerald-500"/><Mood value={metric.neutros} label="Neutro" color="bg-amber-400"/><Mood value={metric.negativos} label="Negativo" color="bg-rose-500"/></div><div className="mt-4 space-y-2">{rows.map(row=><div key={row.departamento_id} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between text-[10px]"><strong>{row.departamento}</strong><span>{row.respostas} respostas</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div className={`h-full ${row.enps>=50?'bg-emerald-500':row.enps>=0?'bg-amber-400':'bg-rose-500'}`} style={{width:`${Math.max(5,Math.min(100,(row.enps+100)/2))}%`}}/></div></div>)}</div></>:<div className="mt-4 rounded-xl border border-dashed border-slate-200 p-5 text-center"><p className="text-xs font-semibold text-slate-600">Aguardando grupo mínimo</p><p className="mt-1 text-[9px] leading-4 text-slate-400">O mapa só aparece quando há respostas suficientes para preservar o anonimato.</p></div>}</section>}
function Mood({value,label,color}:{value:number;label:string;color:string}){return <div className="rounded-xl bg-slate-50 p-2 text-center"><span className={`mx-auto block h-2 w-2 rounded-full ${color}`}/><strong className="mt-1 block text-sm">{value}</strong><span className="text-[8px] text-slate-400">{label}</span></div>}
