import {useCallback,useEffect,useMemo,useState,type ReactNode} from 'react';
import {apiFetch} from '../services/api';
import type {CalibrationLog,OkrItem,PerformanceDashboard,TalentResult} from '../types/performance';

const QUADRANTS=[
  {x:1,y:3,title:'Especialista consistente',subtitle:'Alta entrega · potencial focal',tone:'bg-sky-50 border-sky-200',dot:'bg-sky-500'},
  {x:2,y:3,title:'Alto desempenho',subtitle:'Pronto para ampliar escopo',tone:'bg-teal-50 border-teal-200',dot:'bg-teal-500'},
  {x:3,y:3,title:'Estrela',subtitle:'Sucessor prioritário',tone:'bg-emerald-50 border-emerald-300',dot:'bg-emerald-500'},
  {x:1,y:2,title:'Profissional sólido',subtitle:'Valor consistente na função',tone:'bg-slate-50 border-slate-200',dot:'bg-slate-400'},
  {x:2,y:2,title:'Core player',subtitle:'Desempenho e potencial estáveis',tone:'bg-indigo-50 border-indigo-200',dot:'bg-indigo-500'},
  {x:3,y:2,title:'Talento emergente',subtitle:'Acelerar desenvolvimento',tone:'bg-violet-50 border-violet-200',dot:'bg-violet-500'},
  {x:1,y:1,title:'Sob observação',subtitle:'Plano de recuperação',tone:'bg-rose-50 border-rose-200',dot:'bg-rose-400'},
  {x:2,y:1,title:'Inconsistente',subtitle:'Investigar barreiras de entrega',tone:'bg-amber-50 border-amber-200',dot:'bg-amber-500'},
  {x:3,y:1,title:'Aposta',subtitle:'Potencial ainda não convertido',tone:'bg-orange-50 border-orange-200',dot:'bg-orange-500'},
] as const;

const initials=(name:string)=>name.split(/\s+/).slice(0,2).map((part)=>part[0]).join('').toUpperCase();
const formatDate=(value:string)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const n=(value:unknown)=>Number(value??0);

function normalizeTalent(item:TalentResult):TalentResult{return {...item,resultado_id:n(item.resultado_id),ciclo_id:n(item.ciclo_id),colaborador_id:n(item.colaborador_id),departamento_id:n(item.departamento_id),desempenho:n(item.desempenho),potencial:n(item.potencial),desempenho_calculado:n(item.desempenho_calculado),potencial_calculado:n(item.potencial_calculado),quadrante_x:n(item.quadrante_x) as 1|2|3,quadrante_y:n(item.quadrante_y) as 1|2|3,total_avaliacoes:n(item.total_avaliacoes),versao:n(item.versao)}}

function TalentCard({talent,onDragStart}:{talent:TalentResult;onDragStart:(talent:TalentResult)=>void}){
  const calibrated=talent.desempenho_calibrado!==null&&talent.desempenho_calibrado!==undefined;
  return <article draggable onDragStart={(event)=>{event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',String(talent.resultado_id));onDragStart(talent)}}
    className="group relative cursor-grab rounded-xl border border-white/80 bg-white p-2.5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md active:cursor-grabbing">
    <div className="flex items-center gap-2.5">
      {talent.foto_url?<img src={talent.foto_url} alt="" className="h-9 w-9 rounded-full object-cover ring-2 ring-white"/>:<div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#102f4a] text-[11px] font-bold text-white">{initials(talent.nome)}</div>}
      <div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-slate-900">{talent.nome}</p><p className="truncate text-[10px] text-slate-500">{talent.cargo??talent.departamento}</p></div>
      {calibrated&&<span className="h-2 w-2 rounded-full bg-violet-500" title="Calibrado"/>}
    </div>
    <div className="invisible absolute bottom-[calc(100%+8px)] left-0 z-50 w-64 translate-y-1 rounded-xl bg-[#12263a] p-3 text-white opacity-0 shadow-2xl transition group-hover:visible group-hover:translate-y-0 group-hover:opacity-100">
      <div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{talent.nome}</p><p className="text-[11px] text-slate-300">{talent.departamento} · {talent.cargo??'Cargo não informado'}</p></div><span className="rounded-full bg-white/10 px-2 py-1 text-[10px]">{talent.total_avaliacoes} avaliações</span></div>
      <div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-lg bg-white/10 p-2"><p className="text-[9px] uppercase tracking-wider text-slate-400">Potencial</p><p className="mt-0.5 text-lg font-semibold">{talent.potencial.toFixed(1)}</p></div><div className="rounded-lg bg-white/10 p-2"><p className="text-[9px] uppercase tracking-wider text-slate-400">Desempenho</p><p className="mt-0.5 text-lg font-semibold">{talent.desempenho.toFixed(1)}</p></div></div>
      <p className="mt-2 text-[10px] leading-relaxed text-slate-300">{calibrated?`Calibrado: ${talent.ultima_justificativa??'ajuste colegiado registrado'}`:'Posição calculada pelas respostas 360 ponderadas.'}</p>
      <span className="absolute -bottom-1.5 left-5 h-3 w-3 rotate-45 bg-[#12263a]"/>
    </div>
  </article>;
}

function OkrTree({items,onEdit}:{items:OkrItem[];onEdit:(item:OkrItem)=>void}){
  const children=useMemo(()=>{const map=new Map<number|null,OkrItem[]>();for(const item of items){const key=item.objetivo_pai_id===null?null:n(item.objetivo_pai_id);const normalized={...item,id:n(item.id),objetivo_pai_id:key,progresso:n(item.progresso),valor_atual:n(item.valor_atual),valor_meta:n(item.valor_meta),versao:n(item.versao)};map.set(key,[...(map.get(key)??[]),normalized]);}return map;},[items]);
  const renderNode=(item:OkrItem,depth=0):ReactNode=>{const nested=children.get(item.id)??[];const leaf=nested.length===0;return <div key={item.id} className={depth===0?'rounded-xl border border-slate-200 bg-white p-3':'ml-3 border-l border-slate-200 pl-3 pt-3'}>
    <div className="flex items-start gap-2"><div className="min-w-0 flex-1"><p className="text-[9px] font-semibold uppercase tracking-[.16em] text-slate-400">{item.nivel}</p><p className="mt-0.5 text-xs font-semibold text-slate-800">{item.titulo}</p></div>{leaf&&<button type="button" onClick={()=>onEdit(item)} className="rounded-md px-2 py-1 text-[10px] font-semibold text-teal-700 hover:bg-teal-50">Atualizar</button>}</div>
    <div className="mt-2 flex items-center gap-2"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-500 transition-all" style={{width:`${Math.min(100,item.progresso)}%`}}/></div><span className="w-9 text-right text-[10px] font-semibold text-slate-600">{item.progresso.toFixed(0)}%</span></div>
    {nested.map((child)=>renderNode(child,depth+1))}</div>};
  return <div className="space-y-3">{(children.get(null)??[]).map((root)=>renderNode(root))}</div>;
}

function CalibrationHistory({items}:{items:CalibrationLog[]}){return <div className="space-y-3">{items.length===0?<p className="text-xs text-slate-400">Nenhuma calibração no filtro atual.</p>:items.slice(0,6).map((item)=><div key={item.id} className="flex gap-3"><div className="mt-1 h-2 w-2 shrink-0 rounded-full bg-violet-500"/><div><p className="text-xs font-semibold text-slate-800">{item.colaborador}</p><p className="text-[10px] text-slate-500">{item.quadrante_x_anterior}.{item.quadrante_y_anterior} → {item.quadrante_x_novo}.{item.quadrante_y_novo} · {formatDate(item.calibrado_em)}</p><p className="mt-1 line-clamp-2 text-[10px] leading-relaxed text-slate-500">{item.justificativa}</p></div></div>)}</div>}

export default function GestaoDesempenho(){
  const [data,setData]=useState<PerformanceDashboard|null>(null);const [cycleId,setCycleId]=useState<number|null>(null);const [departmentId,setDepartmentId]=useState<number|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const [dragged,setDragged]=useState<TalentResult|null>(null);const [calibration,setCalibration]=useState<{talent:TalentResult;x:number;y:number}|null>(null);const [reason,setReason]=useState('');const [saving,setSaving]=useState(false);const [okrEdit,setOkrEdit]=useState<OkrItem|null>(null);const [okrValue,setOkrValue]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const query=new URLSearchParams();if(cycleId)query.set('cicloId',String(cycleId));if(departmentId)query.set('departamentoId',String(departmentId));const response=await apiFetch<PerformanceDashboard>(`/performance/dashboard?${query}`);setData(response);setCycleId((current)=>current??response.selectedCycleId);setError('');}catch(err){setError(err instanceof Error?err.message:'Falha ao carregar People Analytics.');}finally{setLoading(false);}},[cycleId,departmentId]);
  useEffect(()=>{void load();},[load]);
  const talents=useMemo(()=>(data?.talents??[]).map(normalizeTalent),[data?.talents]);
  const metrics=useMemo(()=>({stars:talents.filter((item)=>item.quadrante_x===3&&item.quadrante_y===3).length,highPotential:talents.filter((item)=>item.quadrante_x===3).length,calibrated:talents.filter((item)=>item.desempenho_calibrado!==null&&item.desempenho_calibrado!==undefined).length,average:talents.length?talents.reduce((sum,item)=>sum+item.desempenho,0)/talents.length:0}),[talents]);
  const submitCalibration=async()=>{if(!calibration)return;setSaving(true);try{await apiFetch(`/performance/resultados/${calibration.talent.resultado_id}/calibrar`,{method:'POST',body:JSON.stringify({quadranteX:calibration.x,quadranteY:calibration.y,justificativa:reason,versao:calibration.talent.versao})});setCalibration(null);setReason('');setNotice('Calibração registrada com trilha de auditoria.');await load();}catch(err){setError(err instanceof Error?err.message:'Falha ao calibrar.');}finally{setSaving(false);}};
  const recalculate=async()=>{if(!cycleId)return;setSaving(true);try{await apiFetch(`/performance/ciclos/${cycleId}/recalcular`,{method:'POST'});setNotice('Pontuações 360 recalculadas com os pesos do ciclo.');await load();}catch(err){setError(err instanceof Error?err.message:'Falha ao recalcular.');}finally{setSaving(false);}};
  const submitOkr=async()=>{if(!okrEdit)return;setSaving(true);try{await apiFetch(`/performance/okrs/${okrEdit.id}/progresso`,{method:'PATCH',body:JSON.stringify({valorAtual:Number(okrValue),versao:okrEdit.versao})});setOkrEdit(null);setNotice('KR atualizado e objetivos pais recalculados.');await load();}catch(err){setError(err instanceof Error?err.message:'Falha ao atualizar KR.');}finally{setSaving(false);}};
  if(loading&&!data)return <div className="flex min-h-[60vh] items-center justify-center text-sm text-slate-500">Construindo matriz de talentos…</div>;
  return <div className="mx-auto max-w-[1600px] space-y-5">
    <header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[.22em] text-teal-600">People Analytics · Talent Intelligence</p><h1 className="mt-1 font-serif text-3xl font-semibold text-[#102f4a]">Desempenho & Sucessão</h1><p className="mt-1 text-sm text-slate-500">Avaliação 360, calibração colegiada e OKRs conectados em uma única leitura.</p></div><div className="flex flex-wrap gap-2"><select value={cycleId??''} onChange={(e)=>setCycleId(Number(e.target.value))} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-medium text-slate-700 shadow-sm">{data?.cycles.map((cycle)=><option key={cycle.id} value={cycle.id}>{cycle.nome}</option>)}</select><select value={departmentId??''} onChange={(e)=>setDepartmentId(e.target.value?Number(e.target.value):null)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-medium text-slate-700 shadow-sm"><option value="">Todos os setores</option>{data?.departments.map((department)=><option key={department.id} value={department.id}>{department.nome}</option>)}</select><button type="button" onClick={()=>void recalculate()} disabled={saving} className="rounded-xl bg-[#102f4a] px-4 py-2.5 text-xs font-semibold text-white shadow-sm hover:bg-[#173f61] disabled:opacity-50">Recalcular 360</button></div></header>
    {(error||notice)&&<div className={`flex items-center justify-between rounded-xl border px-4 py-3 text-xs ${error?'border-rose-200 bg-rose-50 text-rose-700':'border-teal-200 bg-teal-50 text-teal-700'}`}><span>{error||notice}</span><button type="button" onClick={()=>{setError('');setNotice('')}}>×</button></div>}
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Talentos mapeados" value={talents.length} detail="no recorte selecionado"/><Metric label="Alta potência" value={metrics.highPotential} detail="potencial no nível 3"/><Metric label="Sucessores prioritários" value={metrics.stars} detail="quadrante Estrela"/><Metric label="Desempenho médio" value={`${metrics.average.toFixed(1)}%`} detail={`${metrics.calibrated} calibrações manuais`}/></section>
    <div className="grid gap-5 2xl:grid-cols-[minmax(0,1fr)_330px]">
      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-start justify-between gap-4"><div><h2 className="text-sm font-semibold text-slate-900">Matriz Nine-Box</h2><p className="mt-0.5 text-xs text-slate-500">Arraste um talento para calibrar sua posição. Toda alteração exige justificativa.</p></div><div className="flex items-center gap-2 text-[10px] text-slate-500"><span className="h-2 w-2 rounded-full bg-violet-500"/> Posição calibrada</div></div>
        <div className="grid grid-cols-[24px_minmax(0,1fr)] gap-2"><div className="flex items-center justify-center"><span className="-rotate-90 whitespace-nowrap text-[10px] font-semibold uppercase tracking-[.18em] text-slate-400">Desempenho</span></div><div className="grid grid-cols-1 gap-2 md:grid-cols-3">{QUADRANTS.map((quadrant)=>{const cellTalents=talents.filter((item)=>item.quadrante_x===quadrant.x&&item.quadrante_y===quadrant.y);return <div key={`${quadrant.x}-${quadrant.y}`} onDragOver={(event)=>{event.preventDefault();event.dataTransfer.dropEffect='move'}} onDrop={(event)=>{event.preventDefault();if(dragged&&(dragged.quadrante_x!==quadrant.x||dragged.quadrante_y!==quadrant.y))setCalibration({talent:dragged,x:quadrant.x,y:quadrant.y});setDragged(null)}} className={`relative min-h-44 rounded-xl border p-3 transition ${quadrant.tone} ${dragged?'ring-1 ring-inset ring-slate-300':''}`}><div className="mb-3 flex items-start justify-between gap-2"><div><div className="flex items-center gap-1.5"><span className={`h-2 w-2 rounded-full ${quadrant.dot}`}/><h3 className="text-xs font-semibold text-slate-800">{quadrant.title}</h3></div><p className="mt-0.5 text-[10px] text-slate-500">{quadrant.subtitle}</p></div><span className="rounded-full bg-white/70 px-2 py-0.5 text-[10px] font-semibold text-slate-500">{cellTalents.length}</span></div><div className="grid gap-2 xl:grid-cols-2">{cellTalents.map((talent)=><TalentCard key={talent.resultado_id} talent={talent} onDragStart={setDragged}/>)}</div></div>})}</div><div/><div className="pt-1 text-center text-[10px] font-semibold uppercase tracking-[.18em] text-slate-400">Potencial →</div></div>
      </section>
      <aside className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-[#f8fafc] p-4"><div className="mb-3"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-teal-600">Estratégia conectada</p><h2 className="mt-1 text-sm font-semibold text-slate-900">Cascata de OKRs</h2></div><OkrTree items={data?.okrs??[]} onEdit={(item)=>{setOkrEdit(item);setOkrValue(String(item.valor_atual))}}/></section><section className="rounded-2xl border border-slate-200 bg-white p-4"><h2 className="text-sm font-semibold text-slate-900">Trilha de calibração</h2><p className="mb-4 mt-0.5 text-[10px] text-slate-500">Decisões colegiadas preservadas para auditoria.</p><CalibrationHistory items={data?.calibrations??[]}/></section><section className="rounded-2xl bg-[#102f4a] p-4 text-white"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-teal-300">Privacidade por desenho</p><p className="mt-2 text-xs leading-relaxed text-slate-200">Comentários qualitativos só aparecem após atingir o limiar de anonimato configurado no ciclo. A identidade do avaliador não integra a tabela de feedback textual.</p></section></aside>
    </div>
    {calibration&&<Modal title="Calibração colegiada" onClose={()=>setCalibration(null)}><p className="text-sm text-slate-600"><strong>{calibration.talent.nome}</strong> será movido de {calibration.talent.quadrante_x}.{calibration.talent.quadrante_y} para {calibration.x}.{calibration.y}.</p><label className="mt-4 block text-xs font-semibold text-slate-700">Justificativa da banca</label><textarea value={reason} onChange={(e)=>setReason(e.target.value)} rows={4} maxLength={2000} placeholder="Registre evidências, contexto e consenso da calibração…" className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-violet-400"/><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>setCalibration(null)} className="rounded-lg px-4 py-2 text-xs font-semibold text-slate-600">Cancelar</button><button type="button" disabled={reason.trim().length<10||saving} onClick={()=>void submitCalibration()} className="rounded-lg bg-violet-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">Salvar calibração</button></div></Modal>}
    {okrEdit&&<Modal title="Atualizar Key Result" onClose={()=>setOkrEdit(null)}><p className="text-sm font-semibold text-slate-800">{okrEdit.titulo}</p><p className="mt-1 text-xs text-slate-500">A alteração recalculará recursivamente as metas de departamento e o objetivo corporativo.</p><label className="mt-4 block text-xs font-semibold text-slate-700">Valor atual</label><input type="number" value={okrValue} onChange={(e)=>setOkrValue(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-teal-400"/><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>setOkrEdit(null)} className="rounded-lg px-4 py-2 text-xs font-semibold text-slate-600">Cancelar</button><button type="button" disabled={!Number.isFinite(Number(okrValue))||saving} onClick={()=>void submitOkr()} className="rounded-lg bg-teal-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">Atualizar cascata</button></div></Modal>}
  </div>;
}

function Metric({label,value,detail}:{label:string;value:string|number;detail:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">{label}</p><p className="mt-1 font-serif text-2xl font-semibold text-[#102f4a]">{value}</p><p className="mt-0.5 text-[10px] text-slate-500">{detail}</p></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/55 p-4" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose()}}><div role="dialog" aria-modal="true" aria-label={title} className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="font-serif text-xl font-semibold text-[#102f4a]">{title}</h2><button type="button" onClick={onClose} aria-label="Fechar" className="text-xl text-slate-400">×</button></div><div className="mt-4">{children}</div></div></div>}
