import{randomUUID}from'node:crypto';import{all,withTransaction}from'../../db/client.js';import{calculateUnlockedCourses,gradeQuiz,validateWatchSync}from'../domain/lmsEngine.js';import type{CourseDependencyState,QuizAnswer,QuizQuestionKey,WatchSyncInput}from'../domain/types.js';
type Row=Record<string,unknown>;const error=(message:string,status:number,code:string):Error=>Object.assign(new Error(message),{status,code});

export async function dashboard(collaboratorId:number|null,trailId:number|null,period:'SEMANAL'|'MENSAL'):Promise<Record<string,unknown>>{
  const collaborators=await all(`SELECT id,COALESCE(nome_social,nome_completo) AS nome,departamento_id FROM colaboradores WHERE status='ATIVO' ORDER BY nome_completo`)as Row[];const selectedCollaborator=collaboratorId??Number(collaborators[0]?.id??0);
  const trails=await all(`SELECT * FROM trilhas_aprendizagem WHERE ativa ORDER BY id`)as Row[];const selectedTrail=trailId??Number(trails[0]?.id??0);if(!selectedCollaborator||!selectedTrail)return{collaborators,trails,courses:[],lessons:[],badges:[],leaderboard:[],xp:0};
  const courses=await all(`SELECT c.id,c.titulo,c.descricao,c.carga_minutos,c.nota_minima,c.percentual_video_minimo,c.xp_conclusao,
    tc.ordem,tc.curso_pre_requisito_id,m.id AS matricula_id,m.status,m.progresso_percentual,m.nota_final,m.versao,
    pm.status AS prerequisito_status,pm.nota_final AS prerequisito_nota,pc.nota_minima AS prerequisito_nota_minima
    FROM trilhas_cursos tc JOIN cursos c ON c.id=tc.curso_id
    JOIN matriculas_cursos m ON m.curso_id=c.id AND m.colaborador_id=?
    LEFT JOIN cursos pc ON pc.id=tc.curso_pre_requisito_id
    LEFT JOIN matriculas_cursos pm ON pm.curso_id=tc.curso_pre_requisito_id AND pm.colaborador_id=?
    WHERE tc.trilha_id=? ORDER BY tc.ordem`,[selectedCollaborator,selectedCollaborator,selectedTrail])as Row[];
  const states:CourseDependencyState[]=courses.map((row)=>({courseId:Number(row.id),order:Number(row.ordem),prerequisiteCourseId:row.curso_pre_requisito_id===null?null:Number(row.curso_pre_requisito_id),status:String(row.status),grade:row.nota_final===null?null:Number(row.nota_final)}));const unlocked=calculateUnlockedCourses(states);
  const enriched=courses.map((row)=>({...row,desbloqueado:unlocked.get(Number(row.id))??false}));const courseIds=courses.map((row)=>Number(row.id));
  const lessons=courseIds.length?await all(`SELECT a.*,COALESCE(p.ultimo_segundo,0) AS ultimo_segundo,COALESCE(p.maximo_segundo_assistido,0) AS maximo_segundo_assistido,
    COALESCE(p.tempo_valido_segundos,0) AS tempo_valido_segundos,COALESCE(p.percentual,0) AS percentual,
    COALESCE(p.concluida,false) AS concluida,COALESCE(p.versao,1) AS versao
    FROM aulas a LEFT JOIN aulas_progresso p ON p.aula_id=a.id AND p.colaborador_id=?
    WHERE a.curso_id=ANY(?::bigint[]) ORDER BY a.curso_id,a.ordem`,[selectedCollaborator,courseIds])as Row[]:[];
  const periodStart=period==='SEMANAL'?`date_trunc('week',current_date)::date`:`date_trunc('month',current_date)::date`;
  const[badges,leaderboard,xpRows]=await Promise.all([
    all(`SELECT bc.id AS conquista_id,b.id,b.codigo,b.nome,b.descricao,b.cor_primaria,b.icone,b.xp_bonus,bc.conquistado_em FROM badges_conquistados bc JOIN badges b ON b.id=bc.badge_id WHERE bc.colaborador_id=? ORDER BY bc.conquistado_em DESC`,[selectedCollaborator])as Promise<Row[]>,
    all(`SELECT l.colaborador_id,COALESCE(c.nome_social,c.nome_completo) AS nome,d.nome AS equipe,l.xp,
      rank() OVER (ORDER BY l.xp DESC,l.atualizado_em ASC) AS posicao
      FROM tabela_lideranca l JOIN colaboradores c ON c.id=l.colaborador_id LEFT JOIN departamentos d ON d.id=c.departamento_id
      WHERE l.tipo_periodo=? AND l.periodo_inicio=${periodStart} ORDER BY posicao,c.nome_completo LIMIT 50`,[period])as Promise<Row[]>,
    all(`SELECT COALESCE(SUM(pontos),0)::int AS total FROM xp_eventos WHERE colaborador_id=?`,[selectedCollaborator])as Promise<Row[]>,
  ]);
  return{collaborators,trails,selectedCollaboratorId:selectedCollaborator,selectedTrailId:selectedTrail,courses:enriched,lessons,badges,leaderboard,xp:Number(xpRows[0]?.total??0),period};
}

export async function syncWatch(input:{collaboratorId:number;lessonId:number;idempotencyKey:string;userAgentHash:string;sync:WatchSyncInput}):Promise<Row>{
  return withTransaction(async tx=>{const duplicate=await tx.all(`SELECT p.*,row_to_json(m) AS matricula FROM aulas_eventos_presenca e JOIN aulas_progresso p ON p.aula_id=e.aula_id AND p.colaborador_id=e.colaborador_id JOIN aulas a ON a.id=e.aula_id JOIN matriculas_cursos m ON m.curso_id=a.curso_id AND m.colaborador_id=e.colaborador_id WHERE e.chave_idempotencia=?::uuid`,[input.idempotencyKey])as Row[];if(duplicate[0])return duplicate[0]as Row;
    const lessons=await tx.all(`SELECT a.*,c.percentual_video_minimo FROM aulas a JOIN cursos c ON c.id=a.curso_id WHERE a.id=?`,[input.lessonId])as Row[];const lesson=lessons[0];if(!lesson)throw error('Aula nao encontrada.',404,'LESSON_NOT_FOUND');
    await tx.run(`INSERT INTO aulas_progresso (colaborador_id,aula_id) VALUES (?,?) ON CONFLICT (colaborador_id,aula_id) DO NOTHING`,[input.collaboratorId,input.lessonId]);const progressRows=await tx.all(`SELECT * FROM aulas_progresso WHERE colaborador_id=? AND aula_id=? FOR UPDATE`,[input.collaboratorId,input.lessonId])as Row[];const progress=progressRows[0]as Row;
    const next=validateWatchSync({lastSecond:Number(progress.ultimo_segundo),maxSecond:Number(progress.maximo_segundo_assistido),validSeconds:Number(progress.tempo_valido_segundos),durationSeconds:Number(lesson.duracao_segundos),version:Number(progress.versao)},input.sync,Number(lesson.percentual_video_minimo));
    await tx.run(`INSERT INTO aulas_eventos_presenca (id,colaborador_id,aula_id,chave_idempotencia,sequencia,segundo_inicial,segundo_final,delta_valido,aba_ativa,visibilidade,user_agent_hash)
      VALUES (?::uuid,?,?,?::uuid,?,?,?,?,?,?,?)`,[input.idempotencyKey,input.collaboratorId,input.lessonId,input.idempotencyKey,input.sync.sequence,progress.ultimo_segundo,input.sync.currentSecond,next.validDelta,input.sync.active,input.sync.visibility,input.userAgentHash]);
    const updated=await tx.all(`UPDATE aulas_progresso SET ultimo_segundo=?,maximo_segundo_assistido=?,tempo_valido_segundos=?,percentual=?,concluida=?,ultima_sincronizacao=now(),versao=versao+1 WHERE id=? RETURNING *`,[next.lastSecond,next.maxSecond,next.validSeconds,next.percent,next.completed,progress.id])as Row[];
    const aggregate=await tx.all(`SELECT a.curso_id,MIN(CASE WHEN a.obrigatoria THEN COALESCE(p.percentual,0) ELSE 100 END) AS minimo,AVG(COALESCE(p.percentual,0)) AS media,BOOL_AND(NOT a.obrigatoria OR COALESCE(p.concluida,false)) AS concluidas FROM aulas a LEFT JOIN aulas_progresso p ON p.aula_id=a.id AND p.colaborador_id=? WHERE a.curso_id=? GROUP BY a.curso_id`,[input.collaboratorId,lesson.curso_id])as Row[];const agg=aggregate[0]as Row;
    const enrollments=await tx.all(`UPDATE matriculas_cursos SET progresso_percentual=?,status=CASE WHEN ? THEN 'AGUARDANDO_PROVA' ELSE 'EM_ANDAMENTO' END,iniciado_em=COALESCE(iniciado_em,now()),versao=versao+1 WHERE colaborador_id=? AND curso_id=? RETURNING id,curso_id,status,progresso_percentual,nota_final,versao`,[Number(agg.media),Boolean(agg.concluidas),input.collaboratorId,lesson.curso_id])as Row[];return{...updated[0],matricula:enrollments[0]};
  });
}

export async function startQuiz(collaboratorId:number,courseId:number,attemptId:string):Promise<Row>{return withTransaction(async tx=>{const access=await tx.all(`SELECT q.*,m.status,m.nota_final,(SELECT COUNT(*) FROM provas_tentativas t WHERE t.questionario_id=q.id AND t.colaborador_id=?) AS tentativas FROM questionarios_provas q JOIN matriculas_cursos m ON m.curso_id=q.curso_id AND m.colaborador_id=? WHERE q.curso_id=? AND q.ativo FOR UPDATE`,[collaboratorId,collaboratorId,courseId])as Row[];const quiz=access[0];if(!quiz)throw error('Questionario nao encontrado.',404,'QUIZ_NOT_FOUND');if(!['AGUARDANDO_PROVA','REPROVADO'].includes(String(quiz.status)))throw error('Conclua o video antes de iniciar a avaliacao.',409,'VIDEO_NOT_COMPLETED');if(Number(quiz.tentativas)>=Number(quiz.maximo_tentativas))throw error('Limite de tentativas atingido.',409,'QUIZ_ATTEMPTS_EXHAUSTED');
    const existing=await tx.all(`SELECT * FROM provas_tentativas WHERE questionario_id=? AND colaborador_id=? AND status='EM_ANDAMENTO' AND expira_em>now() ORDER BY iniciada_em DESC LIMIT 1`,[quiz.id,collaboratorId])as Row[];if(existing[0])return existing[0]as Row;
    const questions=await tx.all(`SELECT id,enunciado FROM questionarios_questoes WHERE questionario_id=? AND ativa ORDER BY random() LIMIT ?`,[quiz.id,quiz.quantidade_questoes])as Row[];if(questions.length<Number(quiz.quantidade_questoes))throw error('Banco de questoes insuficiente.',409,'INSUFFICIENT_QUESTIONS');const snapshot=[];for(const question of questions){const alternatives=await tx.all(`SELECT id,texto FROM questionarios_alternativas WHERE questao_id=? ORDER BY random()`,[question.id]);snapshot.push({id:question.id,enunciado:question.enunciado,alternativas:alternatives});}
    const rows=await tx.all(`INSERT INTO provas_tentativas (id,questionario_id,colaborador_id,numero_tentativa,questoes_snapshot,expira_em) VALUES (?::uuid,?,?,?,?::jsonb,now()+(?||' minutes')::interval) RETURNING *`,[attemptId,quiz.id,collaboratorId,Number(quiz.tentativas)+1,JSON.stringify(snapshot),String(quiz.tempo_limite_minutos)])as Row[];return rows[0]as Row;});}

async function awardBadge(tx:any,collaboratorId:number,code:string,courseId:number|null,metadata:Row):Promise<void>{const rows=await tx.all(`SELECT * FROM badges WHERE codigo=? AND ativo`,[code])as Row[];const badge=rows[0];if(!badge)return;const inserted=await tx.run(`INSERT INTO badges_conquistados (colaborador_id,badge_id,curso_id,metadados) VALUES (?,?,?,?::jsonb) ON CONFLICT (colaborador_id,badge_id,curso_id) DO NOTHING`,[collaboratorId,badge.id,courseId,JSON.stringify(metadata)]);if(inserted.rowCount)await tx.run(`INSERT INTO xp_eventos (id,colaborador_id,pontos,origem,referencia_tipo,referencia_id) VALUES (?::uuid,?,?,'BADGE','BADGE',?) ON CONFLICT DO NOTHING`,[randomUUID(),collaboratorId,badge.xp_bonus,String(badge.id)]);}

async function awardCompletion(tx:any,collaboratorId:number,courseId:number,xp:number,title:string):Promise<void>{
  await tx.run(`INSERT INTO xp_eventos (id,colaborador_id,pontos,origem,referencia_tipo,referencia_id) VALUES (?::uuid,?,?,'CURSO','CURSO',?) ON CONFLICT (colaborador_id,origem,referencia_tipo,referencia_id) DO NOTHING`,[randomUUID(),collaboratorId,xp,String(courseId)]);
  await awardBadge(tx,collaboratorId,'PRIMEIRO_PASSO',null,{primeiroCurso:title});
  if(title.toLocaleLowerCase('pt-BR').includes('lgpd'))await awardBadge(tx,collaboratorId,'GUARDIAO_DADOS',courseId,{curso:title});
  const trails=await tx.all(`SELECT t.id,t.nome,t.xp_conclusao,COUNT(tc.curso_id)::int AS total,COUNT(*) FILTER (WHERE m.status='CONCLUIDO')::int AS concluidos FROM trilhas_aprendizagem t JOIN trilhas_cursos tc ON tc.trilha_id=t.id LEFT JOIN matriculas_cursos m ON m.curso_id=tc.curso_id AND m.colaborador_id=? WHERE t.id IN (SELECT trilha_id FROM trilhas_cursos WHERE curso_id=?) GROUP BY t.id,t.nome,t.xp_conclusao`,[collaboratorId,courseId])as Row[];
  for(const trail of trails){if(Number(trail.total)!==Number(trail.concluidos))continue;await tx.run(`INSERT INTO xp_eventos (id,colaborador_id,pontos,origem,referencia_tipo,referencia_id) VALUES (?::uuid,?,?,'TRILHA','TRILHA',?) ON CONFLICT (colaborador_id,origem,referencia_tipo,referencia_id) DO NOTHING`,[randomUUID(),collaboratorId,trail.xp_conclusao,String(trail.id)]);await awardBadge(tx,collaboratorId,'ONBOARDING_MASTER',null,{trilha:trail.nome});}
}

export async function submitQuiz(input:{attemptId:string;collaboratorId:number;answers:QuizAnswer[]}):Promise<Row>{return withTransaction(async tx=>{const rows=await tx.all(`SELECT t.*,q.nota_minima,q.curso_id,c.titulo,c.xp_conclusao FROM provas_tentativas t JOIN questionarios_provas q ON q.id=t.questionario_id JOIN cursos c ON c.id=q.curso_id WHERE t.id=?::uuid AND t.colaborador_id=? FOR UPDATE`,[input.attemptId,input.collaboratorId])as Row[];const attempt=rows[0];if(!attempt)throw error('Tentativa nao encontrada.',404,'ATTEMPT_NOT_FOUND');if(attempt.status!=='EM_ANDAMENTO')throw error('Tentativa ja finalizada.',409,'ATTEMPT_FINISHED');if(new Date(String(attempt.expira_em)).getTime()<Date.now())throw error('Tempo da prova expirado.',409,'ATTEMPT_EXPIRED');const snapshot=attempt.questoes_snapshot as{id:number}[];const ids=snapshot.map(item=>Number(item.id));const correctRows=await tx.all(`SELECT q.id AS questao_id,a.id AS alternativa_id FROM questionarios_questoes q JOIN questionarios_alternativas a ON a.questao_id=q.id AND a.correta WHERE q.id=ANY(?::bigint[])`,[ids])as Row[];const keys:QuizQuestionKey[]=correctRows.map(row=>({questionId:Number(row.questao_id),correctAlternativeId:Number(row.alternativa_id)}));const result=gradeQuiz(keys,input.answers,Number(attempt.nota_minima));for(const answer of input.answers){const key=keys.find(item=>item.questionId===answer.questionId);await tx.run(`INSERT INTO provas_respostas (tentativa_id,questao_id,alternativa_id,correta) VALUES (?::uuid,?,?,?)`,[input.attemptId,answer.questionId,answer.alternativeId,key?.correctAlternativeId===answer.alternativeId]);}
    await tx.run(`UPDATE provas_tentativas SET status='FINALIZADA',nota=?,aprovada=?,finalizada_em=now() WHERE id=?::uuid`,[result.grade,result.approved,input.attemptId]);await tx.run(`UPDATE matriculas_cursos SET nota_final=?,status=?,concluido_em=CASE WHEN ? THEN now() ELSE NULL END,progresso_percentual=CASE WHEN ? THEN 100 ELSE progresso_percentual END,versao=versao+1 WHERE colaborador_id=? AND curso_id=?`,[result.grade,result.approved?'CONCLUIDO':'REPROVADO',result.approved,result.approved,input.collaboratorId,attempt.curso_id]);if(result.approved)await awardCompletion(tx,input.collaboratorId,Number(attempt.curso_id),Number(attempt.xp_conclusao),String(attempt.titulo));return{...result,cursoId:attempt.curso_id};});}

export async function badge(id:number):Promise<Row|null>{const rows=await all(`SELECT * FROM badges WHERE id=? AND ativo`,[id])as Row[];return rows[0]??null;}
